name: e_learning_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash.svg
    - assets/images/onlinelearning.svg
    - assets/images/exams.svg
    - assets/images/certificate.svg
    - assets/images/Certification-bro.svg
    - assets/images/anytime.svg




