name: e_learning_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  smooth_page_indicator: ^1.2.1
  flutter_hooks: ^0.21.2
  auto_route: ^10.1.0+1
  provider: ^6.1.5
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#0961F5"
  image: assets/images/splash.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  web: false

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#0961F5"


